---
- import_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'

- name: install ansible for ansible-pull
  package:
    state: present
    name: ansible
- name: install ansible-pull.timer
  copy:
    src: ansible-pull/
    dest: /etc/systemd/system/
    mode: 0644
- name: refresh systemd
  systemd:
    daemon_reload: yes
- name: start ansible-pull.timer
  systemd:
    name: ansible-pull.timer
    enabled: yes
    state: started
