---
- name: install distro specific packages
  package:
    state: present
    name:
      - dnf-automatic
      - epel-release

- name: start automatic updates
  systemd:
    enabled: yes
    state: started
    name: dnf-automatic-install.timer

- name: disable selinux
  selinux:
    state: permissive
    policy: targeted
  register: selinux

- name: reboot on selinux change
  reboot: {}
  when: selinux.reboot_required
